"""add cascade deletes on categories/references/documents

Revision ID: d21e720e263c
Revises: fa8331707c92
Create Date: 2025-09-18 14:41:22.522641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21e720e263c'
down_revision = 'fa8331707c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('documents_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('documents_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'references', ['reference_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('references_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('references_ibfk_1'), 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('documents_ibfk_2'), 'references', ['reference_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('documents_ibfk_1'), 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
