"""add relations category <-> reference, document <-> category/reference

Revision ID: e6cc49abbd6a
Revises: e3daf616f317
Create Date: 2025-09-14 06:32:01.225943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cc49abbd6a'
down_revision = 'e3daf616f317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('uq_title_author'))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('references', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('uq_title_author'), ['title', 'author'], unique=True)
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
